sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t swissgato/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true swissgato/docker-react npm run test